name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    # Docker Buildx 설정
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # GHCR 로그인
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Docker 이미지 빌드 & 푸시 (캐시 적용)
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        push: true
        # GitHub Actions 캐시 사용
        cache-from: type=gha,scope=frontend
        cache-to: type=gha,mode=max,scope=frontend
        tags: |
          ghcr.io/${{ github.repository_owner }}/frontend:latest
          ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}

    # EC2 배포
    - name: Deploy to EC2
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/app
          ./deploy-frontend.sh ${{ github.sha }}