# name: Frontend CI/CD

# on:
#   push:
#     paths:
#       - 'frontend/**'
#       - '.github/workflows/frontend-deploy.yml'
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
      
#     - name: Set up Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '24'
#         cache: 'npm'
#         cache-dependency-path: frontend/package-lock.json
        
#     - name: Install dependencies
#       working-directory: ./frontend
#       run: npm ci
      
#     - name: Build application
#       working-directory: ./frontend
#       run: npm run build
      
#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v3
#       with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
        
#     - name: Build and push Docker image
#       uses: docker/build-push-action@v6
#       with:
#         context: ./frontend
#         push: true
#         cache-from: type=gha
#         cache-to: type=gha, mode=max
#         tags: |
#           ghcr.io/${{ github.repository_owner }}/frontend:latest
#           ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}
          
#     - name: Deploy to EC2
#       if: github.ref == 'refs/heads/main'
#       uses: appleboy/ssh-action@v1.0.0
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USER }}
#         key: ${{ secrets.EC2_SSH_KEY }}
#         script: |
#           cd /home/ubuntu/app
#           ./deploy-frontend.sh ${{ github.sha }}

name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Docker Buildx 설정
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3️⃣ GHCR 로그인
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 4️⃣ Docker 이미지 빌드 & 푸시 (캐시 적용)
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        push: true
        # GitHub Actions 캐시 사용
        cache-from: type=gha,scope=frontend
        cache-to: type=gha,mode=max,scope=frontend
        tags: |
          ghcr.io/${{ github.repository_owner }}/frontend:latest
          ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}

    # 5️⃣ EC2 배포
    - name: Deploy to EC2
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/app
          ./deploy-frontend.sh ${{ github.sha }}